### ISSUE TITLE
TextView: Word Wrapping is not correct

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#1820]
```csharp

var tv = new TextView();
tv.WordWrap = true;
tv.ReadOnly = true;
tv.Text = "This is the help text for the Second Step.\n\nPress the button demo changing the Title.\n\nIf First Name is empty the step will prevent moving to the next step.";
```

<img width="183" alt="image" src="https://user-images.githubusercontent.com/585482/173963744-ce45e6a1-be65-4662-b405-af987e800930.png">

The spaces at the beginning of the lines in the third sentence should not be there.

**Comment by BDisp** [comment]
`TextView` preserve trailing spaces.

**Comment by tig** [comment]
> `TextView` preserve trailing spaces.

I had forgotten all about that...

Changing `TextView` to set that to false, fixes it:

<img width="402" alt="image" src="https://user-images.githubusercontent.com/585482/173965401-14d1adf5-04f8-45b8-8580-ec12d4e8c69d.png">

<img width="196" alt="image" src="https://user-images.githubusercontent.com/585482/173965292-24fe3bcf-e7c0-4c3f-b848-98a204be1fb7.png">

Can anyone think of a reason why this should not be fixed in `TextView`?

**Comment by BDisp** [comment]
You must ensure that there are blank spaces at the end and if it does not fit the end, it should be placed at the beginning of the next line.

**Comment by tig** [comment]
> You must ensure that there are blank spaces at the end and if it does not fit the end, it should be placed at the beginning of the next line.

Sorry, I'm not sure what you mean by this.

**Comment by BDisp** [comment]
> Sorry, I'm not sure what you mean by this.

In a `Label` the spaces are removed in the end of the line but in the `TextView` it's need to copy and past. So the spaces are necessary.

**Comment by tig** [comment]
I still don't understand.

My question is simple: If we change that single line of code in `TextView` such that `preseveTrailingSpces` is false instead of true, will it break anything else?

**Comment by BDisp** [comment]
> My question is simple: If we change that single line of code in `TextView` such that `preseveTrailingSpces` is false instead of true, will it break anything else?

Yes, because if you select two lines the last word of the first line will be joined with the first word of the next line. Yes, because if you select two lines the last word of the first line will be joined with the first word of the next line.

**Comment by BDisp** [comment]
> Instead, if I understand correctly, we need a more comprehensive fix that has the VISUAL effect of `preserveTrailingSpaces = false` but does not change the underlying text when applied. Correct?

More or less, I admit that may have some issue in the case where the vertical scroll bar isn't sending the correct information if it's not visible, but also there are cases where you don't have no choices to avoid starting a line with a space. Here a example with the `"Hello tig"` with a width of 5:
```
Hello
 tig

```
In these cases you have to put the space at the begin of a line.

**Comment by tig** [comment]
The right long-term fix is to have `TextView`'s rendering codepath be separate from storage. This way `preserveTrailingSpaces` can apply only to how text is displayed. 

For now, I've modified my fix to be more surgical, effectively: If `TextView.ReadOnly == true && TextView.WordWrap == true` then `preserveTrailingSpaces = false`. In this case, there is a small risk a user will use the clipboard to copy text from the TextView and the text will not match what was originally `set`. 

What do you think of this?

**Comment by BDisp** [comment]
As you said it's a risk, if many people who copy from a read only text to paste elsewhere. But that doesn't matter because currently `TextView` is copying the spaces more the line breaks, which do not correspond to the correct text :-)

**Comment by BDisp** [comment]
But I'm seeing now that the length of the text is not the same and this is because it's not counting the ending spaces. At the time when I implemented that, I faced that difficulties.

**Comment by tig** [comment]
Coming back to this...

Here's the latest with this PR applied:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/585482/180457265-065b21f4-a7f1-4d3e-8e31-a4b817f7f389.png">

As you noted, the length of the copied text is incorrect. 

> **Edit:** But I'm seeing now by the image that was resolved by your fix. Please copy with a not read only wrapped text and paste. If it paste incorrect then a good solution is if is not read only change to read only to copy and after change again to state before. Can you do that, please?

@BDisp I am not following what you are suggesting here. Can you please restate? Thanks.

**Comment by BDisp** [comment]
This is already fixed with my last pr #1867. Now the copy/paste always unwrap the text before.

**Comment by BDisp** [comment]
If you allow, I suggest you can use the `Dim.Percent` on the Wizard class to allow the view always stay visible on resizing.

**Comment by tig** [comment]
> This is already fixed with my last pr #1867. Now the copy/paste always unwrap the text before.

"This" being copy/paste working correctly. However, by default the Textview still doesn't word-wrap correctly when read-only is true:

<img width="575" alt="image" src="https://user-images.githubusercontent.com/585482/180582351-9d8da0bb-b0a5-4c3d-8ae2-c8b2606ac5ca.png">

My PR https://github.com/migueldeicaza/gui.cs/pull/1822 should fix *This* issue (#1820).

Just trying to be as clear as possible.

**Comment by tig** [comment]
> If you allow, I suggest you can use the `Dim.Percent` on the Wizard class to allow the view always stay visible on resizing.

I'm not sure what you mean. Is there a bug in the current Wizard implementation that an Issue should be filed against?

**Comment by BDisp** [comment]
> I'm not sure what you mean. Is there a bug in the current Wizard implementation that an Issue should be filed against?

The `TextView` text is truncated.

![wizard-broken](https://user-images.githubusercontent.com/13117724/180603290-c1ffdea2-74a2-4e50-9c84-a5f90906ce76.gif)

**Comment by BDisp** [comment]
> "This" being copy/paste working correctly. However, by default the Textview still doesn't word-wrap correctly when read-only is true:

You are right @tig, sorry. I made confusion about the copy/paste behavior when word wrap is true. In the case when read only is also true your fix almost fix it, but see this video where copy from read only and paste will cut off the last number 7.

![textview-readonly-wrap](https://user-images.githubusercontent.com/13117724/180604328-a411e1a3-c528-48a6-96c4-fb84f429d46c.gif)

**Comment by tig** [comment]
> > I'm not sure what you mean. Is there a bug in the current Wizard implementation that an Issue should be filed against?
> 
> The `TextView` text is truncated.
> 
> ![wizard-broken](https://user-images.githubusercontent.com/13117724/180603290-c1ffdea2-74a2-4e50-9c84-a5f90906ce76.gif) [ ![wizard-broken](https://user-images.githubusercontent.com/13117724/180603290-c1ffdea2-74a2-4e50-9c84-a5f90906ce76.gif) ](https://user-images.githubusercontent.com/13117724/180603290-c1ffdea2-74a2-4e50-9c84-a5f90906ce76.gif) [ ](https://user-images.githubusercontent.com/13117724/180603290-c1ffdea2-74a2-4e50-9c84-a5f90906ce76.gif)

That's not the TextView, that's the fact the Wizard is modal and is not resizing. Dialog does this too.

**Comment by BDisp** [comment]
> That's not the TextView, that's the fact the Wizard is modal and is not resizing. Dialog does this too.

I know that's not the `TextView`. I was referring the `Wizard` might use a `Dim.Percent(value)` to accommodate as possible the views in a lower spacing on resizing.

**Comment by tig** [comment]
Yes, you are right. But the fix should go in Dialog.

-cek
Sent via mobile. Expect brevity, typos, and dangerous driving.
________________________________

**Comment by BDisp** [comment]
@tig I submitted a pr to your branch https://github.com/tig/gui.cs/tree/fix_textview_wrap with the fix for `TextView` concern to the behavior of the read only when word wrap is true. Now the cursor position is always correct, also the selected text and copy.

**Comment by tig** [comment]
> @tig I submitted a pr to your branch https://github.com/tig/gui.cs/tree/fix_textview_wrap with the fix for `TextView` concern to the behavior of the read only when word wrap is true. Now the cursor position is always correct, also the selected text and copy.

Thank you! I'll look asap.

**Comment by tig** [comment]
@BDisp can you fix the merge issues in your private PR? I think you just need to merge from `develop` first.

**Comment by BDisp** [comment]
> @BDisp can you fix the merge issues in your private PR? I think you just need to merge from `develop` first.

Done.
